### ISSUE TITLE
More than one nested scroll view in the same ToolbarLayout

### ISSUE THREAD

**Issue by BlackMesa123** [Lijukay/Quotes#1]
When using ToolbarLayout you should use only one nested scroll view as direct child (so either NestedScrollView or RecyclerView), otherwise you'll have issues when scrolling.

https://github.com/Lijukay/Quotes/blob/6419a1e25a3c45dd54b52741edb7989c7e449270/app/src/main/res/layout/activity_main.xml#L11

Simply remove NestedScrollView from your main layout.

**Comment by Lijukay** [comment]
Thank you for the information. I saw that but I am not sure if I already removed it 😁

**Comment by Lijukay** [comment]
Now I removed it. Thank you for reporting that <3
