### ISSUE TITLE
Wrong Layout-Look

### ISSUE THREAD

**Issue by Lijukay** [Lijukay/Quotes#2]
Any TextView will not be fully shown because of the wrong padding.

**Comment by BlackMesa123** [comment]
You could wrap your TextView inside a FrameLayout to center it:
```xml
<dev.oneuiproject.oneui.layout.ToolbarLayout ...>

    <androidx.core.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fillViewport="true"
        app:layout_location="main_content">

        <FrameLayout
            android:id="@+id/main_content"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:text="@string/persons"
                android:textAppearance="@style/TextAppearance.AppCompat.Title" />

        </FrameLayout>

    </androidx.core.widget.NestedScrollView>

</dev.oneuiproject.oneui.layout.ToolbarLayout>
```
In your PersonsActivity class you could also add a listener for the AppBarLayout to center the view when the AppBar expands/collapses:
```java
ToolbarLayout tl = findViewById(R.id.toolbar_persons);
tl.getAppBarLayout().addOnOffsetChangedListener((appBarLayout, verticalOffset) -> {
    final int totalScrollRange = appBarLayout.getTotalScrollRange();
    FrameLayout content = findViewById(R.id.main_content);
    if (content != null) {
        content.setTranslationY(((float) (Math.abs(verticalOffset) - totalScrollRange)) / 2.0f);
    }
});
```

**Comment by Lijukay** [comment]
Thank you very much.


May I ask what

ToolbarLayout tl = findViewById(R.id.toolbar_persons);
tl.getAppBarLayout().addOnOffsetChangedListener((appBarLayout, verticalOffset) -> {
    final int totalScrollRange = appBarLayout.getTotalScrollRange();
    FrameLayout content = findViewById(R.id.main_content);
    if (content != null) {
        content.setTranslationY(((float) (Math.abs(verticalOffset) - totalScrollRange)) / 2.0f);
    }
});

will make?

**Comment by BlackMesa123** [comment]
As I said it adds a simple animation to keep the view always centered even when collapsing/expanding the Appbar:

https://user-images.githubusercontent.com/13062958/181211069-2bad7bf1-b2a6-4391-a8cc-ab6ec0e6e166.mp4

**Comment by Lijukay** [comment]
I see. Thank you very much. I will totally add it. It looks beautiful.

Thank you so much
