### ISSUE TITLE
One UI SwipeRefresh

### ISSUE THREAD

**Issue by BlackMesa123** [Lijukay/Quotes#6]
You probably want to use Samsung's SwipeRefreshLayout instead of stock Google one:
```groovy
implementation 'io.github.oneuiproject.sesl:swiperefreshlayout:1.0.0'
```

<img loading="lazy" src="https://user-images.githubusercontent.com/13062958/183288546-b9634e30-714a-4a09-8716-8a1fba0fd97f.jpg" width="400"/> <img loading="lazy" src="https://user-images.githubusercontent.com/13062958/183288551-27171510-95e5-462b-a4f8-dfa46f550d25.jpg" width="400"/>

**Comment by Lijukay** [comment]
You are right. I wasn't sure if i can implement it. I will do it right away. Thank you so much
